### ISSUE TITLE
Website does not work on Microsoft Edge

### ISSUE THREAD

**Issue by ceifa** [stevenwaterman/narration.studio#1]
![image](https://user-images.githubusercontent.com/26205666/97511499-ff447580-1965-11eb-8da9-3d4f4a019a2f.png)

Microsoft Edge is based on chromium, so I guess it should work fine.

**Comment by stevenwaterman** [comment]
Fair point, I'll have a look through the compatibility tables and add it to the list of allowed browsers. It would definitely fall into the "untested but probably works" category though

**Comment by stevenwaterman** [comment]
Added Edge 79+ to the list of supported browsers. Should take about 10 mins to deploy, if it's still not working let me know - I'm a Linux user so can't check!

**Comment by stevenwaterman** [comment]
Gonna assume this is fixed unless anyone says otherwise - closing

**Comment by ceifa** [comment]
Sorry for the late response, still not working :(

**Comment by ceifa** [comment]
I guess we just have to change the satisfy condition on App.svelte

**Comment by stevenwaterman** [comment]
I can remember doing exactly that, and pushing it - but now I can't see the commit? I guess that would explain why it wasn't fixed, but still very weird. Maybe I forgot to push it or something. Anyway, I've fixed it for real this time.
